# Basic workflow to see Outputs
name: Output

# Running Workflow Manually
on:
  workflow_dispatch:
    inputs:
#       name:
#         type: choice
#         description: Who to greet
#         options: 
#         - monalisa
#         - cschleiden
      message:
        required: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:    
    
      - name: Print Env
        env:
          GIT_REPO: ${{ github.repository }}
          GIT_REPO_O: ${{ github.repository_owner }}
          GIT_T: ${{ secrets.GITHUB_TOKEN }}
        run: |
         echo "$GITHUB.REPOSITORY"
         env
         

           
#       - name: Repo Dispatch
#         env: 
#           DEPLOYMENT_NOTIFICATION_URL: https://api.github.com/repos/toshi-brat/FosFor/dispatches
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#         run: |
#           curl \
#            -X POST \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: Bearer ${{ secrets.GIT_PAT}} " \
#            https://api.github.com/repos/toshi-brat/FosFor/dispatches \
#            -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'

     
        
   
     
