# Basic workflow to see Outputs
name: Output

# Running Workflow Manually
on:
  workflow_dispatch:

jobs:
#Taking A Output "Hello" form a step and Storing it in OUTPUTS
  job1:
    runs-on: ubuntu-latest
    outputs:
       output1: ${{ steps.first.outputs.output }}
    steps:
      - id: first
        run: echo "::set-output name=output::hello"
        name: taking output
        
 # Using NEEDS to run job sequentially and using output of job1 in job2             
  job2:
    runs-on: ubuntu-latest
    
    steps:
      - name: using job1 output
        run: echo ${{needs.job1.outputs.output1}}
        
      



     
        
   
     
