# Basic workflow to see Outputs
name: Output

# Running Workflow Manually
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:    
           
      - name: Repo Dispatch
        env: 
          DEPLOYMENT_NOTIFICATION_URL: https://api.github.com/repos/toshi-brat/FosFor/dispatches
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GIT.PAT}} " \
           https://api.github.com/repos/toshi-brat/terraform_code/dispatches \
           -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'

     
        
   
     
